// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ejemplo2

#include "ui.h"

void buttonled1(lv_event_t * e)
{
	// Your code here
}

void buttonled2(lv_event_t * e)
{
	// Your code here
}
