################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/DELL/Documents/GitHub/EspecializacionSTM32/STemWin/Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery.c \
C:/Users/DELL/Documents/GitHub/EspecializacionSTM32/STemWin/Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_io.c \
C:/Users/DELL/Documents/GitHub/EspecializacionSTM32/STemWin/Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_lcd.c \
C:/Users/DELL/Documents/GitHub/EspecializacionSTM32/STemWin/Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_sdram.c \
C:/Users/DELL/Documents/GitHub/EspecializacionSTM32/STemWin/Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_ts.c 

OBJS += \
./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery.o \
./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_io.o \
./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_lcd.o \
./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_sdram.o \
./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_ts.o 

C_DEPS += \
./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery.d \
./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_io.d \
./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_lcd.d \
./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_sdram.d \
./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_ts.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery.o: C:/Users/DELL/Documents/GitHub/EspecializacionSTM32/STemWin/Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery.c Drivers/BSP/STM32F429I_Discovery/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DUSE_STM32F429I_DISCO -DUSE_USB_HS -DSTM32F429xx -c -I../../Core/Inc -I../../Config -I../../Gui/Target -I../../Modules/filebrowser -I../../Utilities/CPU -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32F429I-Discovery -I../../Drivers/BSP/Components/Common -I../../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc -I../../Middlewares/ST/STemWin/inc -I../../Middlewares/Third_Party/FatFs/src -I../../Middlewares/Third_Party/FatFs/src/drivers -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_io.o: C:/Users/DELL/Documents/GitHub/EspecializacionSTM32/STemWin/Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_io.c Drivers/BSP/STM32F429I_Discovery/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DUSE_STM32F429I_DISCO -DUSE_USB_HS -DSTM32F429xx -c -I../../Core/Inc -I../../Config -I../../Gui/Target -I../../Modules/filebrowser -I../../Utilities/CPU -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32F429I-Discovery -I../../Drivers/BSP/Components/Common -I../../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc -I../../Middlewares/ST/STemWin/inc -I../../Middlewares/Third_Party/FatFs/src -I../../Middlewares/Third_Party/FatFs/src/drivers -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_lcd.o: C:/Users/DELL/Documents/GitHub/EspecializacionSTM32/STemWin/Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_lcd.c Drivers/BSP/STM32F429I_Discovery/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DUSE_STM32F429I_DISCO -DUSE_USB_HS -DSTM32F429xx -c -I../../Core/Inc -I../../Config -I../../Gui/Target -I../../Modules/filebrowser -I../../Utilities/CPU -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32F429I-Discovery -I../../Drivers/BSP/Components/Common -I../../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc -I../../Middlewares/ST/STemWin/inc -I../../Middlewares/Third_Party/FatFs/src -I../../Middlewares/Third_Party/FatFs/src/drivers -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_sdram.o: C:/Users/DELL/Documents/GitHub/EspecializacionSTM32/STemWin/Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_sdram.c Drivers/BSP/STM32F429I_Discovery/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DUSE_STM32F429I_DISCO -DUSE_USB_HS -DSTM32F429xx -c -I../../Core/Inc -I../../Config -I../../Gui/Target -I../../Modules/filebrowser -I../../Utilities/CPU -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32F429I-Discovery -I../../Drivers/BSP/Components/Common -I../../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc -I../../Middlewares/ST/STemWin/inc -I../../Middlewares/Third_Party/FatFs/src -I../../Middlewares/Third_Party/FatFs/src/drivers -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_ts.o: C:/Users/DELL/Documents/GitHub/EspecializacionSTM32/STemWin/Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_ts.c Drivers/BSP/STM32F429I_Discovery/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DUSE_STM32F429I_DISCO -DUSE_USB_HS -DSTM32F429xx -c -I../../Core/Inc -I../../Config -I../../Gui/Target -I../../Modules/filebrowser -I../../Utilities/CPU -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32F429I-Discovery -I../../Drivers/BSP/Components/Common -I../../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc -I../../Middlewares/ST/STemWin/inc -I../../Middlewares/Third_Party/FatFs/src -I../../Middlewares/Third_Party/FatFs/src/drivers -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-BSP-2f-STM32F429I_Discovery

clean-Drivers-2f-BSP-2f-STM32F429I_Discovery:
	-$(RM) ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery.cyclo ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery.d ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery.o ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery.su ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_io.cyclo ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_io.d ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_io.o ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_io.su ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_lcd.cyclo ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_lcd.d ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_lcd.o ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_lcd.su ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_sdram.cyclo ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_sdram.d ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_sdram.o ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_sdram.su ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_ts.cyclo ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_ts.d ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_ts.o ./Drivers/BSP/STM32F429I_Discovery/stm32f429i_discovery_ts.su

.PHONY: clean-Drivers-2f-BSP-2f-STM32F429I_Discovery

